### ISSUE TITLE
M5.Axp.isCharging() doesn't work - please port fix from M5Stack

### ISSUE THREAD

**Issue by patfelst** [tobozo/ESP32-Chimera-Core#62]
Hi there, can you please implement this fix? I tested it by editing the library source and the fix works.
https://github.com/m5stack/M5Core2/issues/1

Thanks

**Comment by tobozo** [comment]
thanks for your warmful comments :+1: 

Since release 1.2.2, ESP32-Chimera-Core enables touch emulation of `BtnA`, `BtnB` and `BtnC` **on M5Core2 only**, so you get native support for pressed, justPressed, justReleased, etc, but only after the display has started.

Although LovyanGFX has an auto-detection feature, this emulation mode will not be enabled without `board = m5stack-core2` in your `platformio.ini`.

The default debounce time for buttons emulation is set to 100ms (lower values throws more false positives).
It can be changed at runtime using `Button::setDebounce( uint32_t ms )`.

LovyanGFX implements `getTouch(&x, &y)` as a TFT_eSPI legacy but has a more comprehensive method:

```C
lgfx::touch_point_t tp; 
// 'number' is how many touch events are currently queued
uint16_t number = M5.Lcd.getTouch(&tp, 1); // second argument is for multitouch, doesn't apply to M5Core2 but needs to be set
if( number > 0 ) {
  // do something with tp.x and tp.y
}
```

New release is published in platformio btw, might take more time for arduino registry

**Comment by patfelst** [comment]
I've had good success using getTouch over the last couple of days, I've basically coded my own "hotzone" type functions, but thanks for all the good information re BtA etc.

The update is already available for update in platformio - I updated and battery charging flag is confirmed fixed!
